export const HTTP_ACTION = "HTTP_ACTION";

export const CREATE_EVENT = "CREATE_EVENT";
export const CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";

export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";
export const DELETE_EVENT_SUCCSESS = "DELETE_EVENT_SUCCSESS";

export const EDIT_EVENT = "EDIT_EVENT";
export const EDIT_EVENT_FAILURE = "EDIT_EVENT_FAILURE";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";